# Generated by Django 5.1 on 2024-08-31 15:25

import adharcard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adharcard', '0002_img_load_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_load',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[adharcard.models.filename]),
        ),
    ]
