# Generated by Django 5.1 on 2024-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adharcard', '0006_alter_img_load_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_load',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
